include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
